const data = {
  products: [
    {
      // _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      image: '/images/p1.jpg',
      brand: 'Nike',
      category: 'Shirts',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      image: '/images/p2.jpg',
      brand: 'Adidas',
      category: 'Shirts',
      description: 'high quality shirt',
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      image: '/images/p3.jpg',
      brand: 'Nike',
      category: 'Pants',
      description: 'high quality product',
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
    },
    {
      // _id: '4',
      name: 'Adidas Slim Pant',
      slug: 'adidas-slim-pant',
      image: '/images/p4.jpg',
      brand: 'Adidas',
      category: 'Pants',
      description: 'high quality product',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
export default data;
